name: Build postmarketOS

on:
  workflow_dispatch: # 支持手动点击运行

jobs:
  build_gemini:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip openssl qemu-user-static binfmt-support curl
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          cd pmbootstrap
          chmod +x pmbootstrap.py
          # 使用绝对路径建立软链接，这样在任何地方都能执行 pmbootstrap
          sudo ln -sf $(pwd)/pmbootstrap.py /usr/local/bin/pmbootstrap
          cd ..

      - name: Initialize pmbootstrap
        run: |
          pmbootstrap init \
            --arch armv7 \
            --device xiaomi-gemini \
            --mirror http://mirror.postmarketos.org/postmarketos/ \
            --repository edge \
            --ui phosh \
            --non-interactive

            pmbootstrap pull


      - name: Build rootfs
        run: |
          pmbootstrap install --password "1234" --no-fsprogs

      - name: Export Images
        run: |
          mkdir -p $HOME/output
          pmbootstrap export $HOME/output
          ls -lh $HOME/output  # 调试输出，确认有文件

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pmos-xiaomi-gemini
          path: ${{ github.workspace }}/output/*
